apiVersion: v1
kind: Pod

metadata:
  name: nginx-storage-pod

spec:
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-storage

  volumes:
  - name: nginx-storage
    persistentVolumeClaim:
      claimName: my-pvc
